GET http://localhost:8080/person

###

GET http://localhost:8080/person/1232421312312323

###

POST http://localhost:8080/person HTTP/1.1
Content-Type: application/json

{
    "_id": 1232421312312323,
    "firstName": "Stewart",
    "lastName": "Rowley",
    "career": "Web Development",
    "degree": "Software Engineering",
    "location": "Walla Walla, Washington"
}

###

GET http://localhost:8080/about

###

GET http://localhost:8080/about/1232421312312323

###

POST http://localhost:8080/about HTTP/1.1
Content-Type: application/json

{
  "_id": 1232421312312323,
  "firstName": "Stewart",
  "lastName": "Rowley",
  "career": "Web Development",
  "degree": "Software Engineering",
  "location": "Walla Walla, Washington",
  "introduction": "I was born in Walla Walla, Washington in 1998. I grew up in a family of nine siblings, including myself. I have four brothers and four sisters and am the third youngest in my family. I met my wife in Walla Walla, Washington when she moved in, right before I left for a two-year mission for The Church of Jesus Christ. After high school I went on a mission to Fort Worth, Texas serving and teaching the people there. When I got home from serving, I got married to my wife Emily after dating for a few months. I went to college at BYU-Idaho to get my bachelor’s degree in Software Engineering with an emphasis in web development. I tried out a few other majors but found that I have a passion for Web Development. I love doing it and creating something out of code like a puzzle, to see the bigger picture when it all comes together. I love how web development allows me to always be learning new skills to become even better at what I enjoy doing for myself and for others.",
  "profile_image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2172.jpg",
  "interest": [
    {
      "name": "Movies",
      "icon": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Icons/icons8-cinema-64.png",
      "description": "These are some of the following favorite movies I like, as follows:",
      "titles": [
        {
          "name": "How to Train Your Dragon",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/how-to-train-your-dragon.jpg",
          "summary": "I first fell in love with this movie because I like fantasy and I always thought dragons, and especially the idea of riding and flying with them, sounded cool. I grew to like the movie more with each new one that came out. I saw the characters develop and remind me of my own relationships and life journey. I think it has a great message of courage, leadership, and compassion. This movie was made in 2010 and was based on a book about Hiccup who is an awkward guy who trains to fight dragons but ends up befriending one and learns how to ride him. Together they convince the whole village that dragons are not their enemies, but rather, they can be the best of friends."
        },
        {
          "name": "Star Wars: Return of the Jedi",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/star-wars.jpg",
          "summary": "Star Wars: Return of the Jedi- I love all the original star wars movies, one through six, but this one is my favorite movie. I like it because of the comeback Luke makes in rescuing and helping others and seeing his new Jedi skills come to life is pretty cool as he defeats evil and the dark side. One cool fact about the movie I learned was that Yoda was never supposed to be in this movie but was added later."
        },
        {
          "name": "Shang Chi",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/shang-chi.jpg",
          "summary": "I think this movie is really great all around. It has a good moral to the story and the character’s relationships are believable and connect well. I also think the hand to hand combat is well done and nice to see compared to other marvel movies because there is a lot of skill involved. I like how it has a storyline along with the action instead of just action and blowing stuff up. I like how it tells a good story."
        }
      ]
    },
    {
      "name": "Board Games",
      "icon": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Icons/icons8-board-game-64.png",
      "description": "I have found board games to be one of my favorite things to do with others. Here are some of my favorite Board games, as follows: ",
      "titles": [
        {
          "name": "Scythe",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/scythe.jpg",
          "summary": "This was a game I was first introduced to by my brothers. We love to play games together especially strategic games that involve conquering or competition. I have now learned the game well and have taught my wife how to play. We have played together a few times now, but it is a longer game that requires a lot of thought, so we haven’t really played it since having a baby. In Scythe, each player represents a leader attempting to restore their honor and lead their faction to power. Players conquer territory, enlist new recruits, reap resources, gain villagers, build structures, and activate powerful mechs. I love that there are many ways to win and how it plays out differently each time. "
        },
        {
          "name": "Pandemic",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/pandemic.jpg",
          "summary": "At first I wasn’t a fan of this game, but after playing it with our friends we became determined to win after so many losses. I grew to love the challenge and the teamwork this game brought to the table and the many different challenges that could be added and conquered from the expansions. Pandemic is a cooperative board game where players work as a team of different people and abilities, to treat infections around the world while finding cures."
        },
        {
          "name": "Wingspan",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/wingspan.webp",
          "summary": "I got this game after really loving Scythe and its gameplay, so I decided to see what other games this company made to see if those would be just as good. I was pleasantly surprised when I discoveredWingspan was quality made and playing it with my wife was lots of fun. You also get to learn cool facts about birds and I love the many different ways to earn points and interact with your own personal board. Wingspan is a four round game where players have their own personal objectives and board to place bird cards and act on their abilities to fulfill their objective and get points for each round and end of the game."
        }
      ]
    },
    {
      "name": "NHL Hockey",
      "icon": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Icons/icons8-hockey-64.png",
      "description": "I love watching NHL hockey and I also love doing fantasy hockey. My most favorite team is the Seattle Kraken but I do love some other teams to. These are the teams as follows:",
      "titles": [
        {
          "name": "Buffalo Sabres",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/buffalo-sabres.jpg",
          "summary": "Buffalo sabres- a team that was established in 1970 in New York. I think New York is a neat city. Also I think the meaning behind their name is pretty special.The team name was chosen because owner Seymour Knox felt a sabre was a weapon carried by a leader, also noting it is swift and strong on offense, as well as defense."
        },
        {
          "name": "Colorado Avalanches",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/colorado-avalanches.jpg",
          "summary": "I have a brother and his family in Colorado so I think it’s fun to support local teams as well as teams that are also where my family is. They have one three stanley cups which means they are a decent team and I think they play really well and their team colors are good ones."
        },
        {
          "name": "Dallas Stars",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/dallas-stars.jpg",
          "summary": "I like this team because I served my mission in Texas and so any Texas team will have some kind of place in my heart, plus they have a really good goalie this year and some decent players."
        },
        {
          "name": "Pittsburgh Penguins",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/pittsburgh-penguins.jpg",
          "summary": "My sister and her family actually moved to Pittsburgh and have been able to see this team practice which I think is cool. This team also has a place in my heart because they are where family is so I feel like there is some connection there. I also think they have the best logo with the penguin with a hockey stick."
        },
        {
          "name": "Seattle Kraken",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/seattle-kraken.jpg",
          "summary": "Seattle Kraken: I first got into hockey with this team since it is my local team. It is only their second year playing so I was hesitant to start supporting them since last year they didn’t do very good, but this year they have really turned around and now have multiple wins and have had some exciting games to watch. My wife and I even got Seattle Kraken hockey jerseys to represent, as well as little baby Kraken onesies for our little one."
        },
        {
          "name": "Toronto Maple Leafs",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/toronto-maple-leafs.jpg",
          "summary": "They are a Canadian team that play as a part of the NHL league, and right now have 17 wins this season, which is a lot. Even though the last time they won the title was in 1967 which is the longest time between a title in NHL history so far! So it’s okay to riot for the underdogs sometimes!"
        },
        {
          "name": "Vegas Knights",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/vegas-knights.jpg",
          "summary": "Three are another local team that was founded a bit later than some others, in 2017. Their main logo is a knight helmet, and then the secondary logo is two crossing swords behind a red star, designed to resemble the star found on the landmark Welcome to Fabulous Las Vegas sign."
        }
      ]
    }
  ]
}


###

PUT http://localhost:8080/about/1232421312312323 HTTP/1.1
Content-Type: application/json

{
  "_id": 1232421312312323,
  "firstName": "Stewart",
  "lastName": "Rowley",
  "career": "Web Development",
  "degree": "Software Engineering",
  "location": "Walla Walla, Washington",
  "introduction": "I was born in Walla Walla, Washington in 1998. The family I grew up in was 9 siblings including me. I had 4 brothers and 4 sisters. I am the third youngest in my famliy. I met my wife in Walla Walla Washington before I left for a 2 year mission for the church of Jesus Christ. I went on a mission for the church of Jesus Christ in Fort Woth, Texas. After my mission I got married to Emily Hepworth. I went to college at BYU-Idaho to get my Bachelors degree in Software Engineering. With an emphasis in the Web development. I have a passion for Web Development and love doing it. ",
  "profile_image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2172.jpg",
  "interest": [
    {
      "name": "Movies",
      "icon": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Icons/icons8-cinema-64.png",
      "description": "These are some of the following favorite movies I like, as follows:",
      "titles": [
        {
          "name": "How to Train Your Dragon",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/how-to-train-your-dragon.jpg",
          "summary": ""
        },
        {
          "name": "Star Wars: Return of the Jedi",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/star-wars.jpg",
          "summary": ""
        },
        {
          "name": "Shang Chi",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/shang-chi.jpg",
          "summary": ""
        }
      ]
    },
    {
      "name": "Board Games",
      "icon": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Icons/icons8-board-game-64.png",
      "description": "I have found board games to be one of my favorite things to do with others. Here are some of my favorite Board games, as follows: ",
      "titles": [
        {
          "name": "Scythe",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/scythe.jpg",
          "summary": ""
        },
        {
          "name": "Pandemic",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/pandemic.jpg",
          "summary": ""
        },
        {
          "name": "Wingspan",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/wingspan.webp",
          "summary": ""
        }
      ]
    },
    {
      "name": "NHL Hockey",
      "icon": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Icons/icons8-hockey-64.png",
      "description": "I love watching NHL hockey and I also love doing fantasy hockey. My most favorite team is the Seattle Kraken but I do love some other teams to. These are the teams as follows:",
      "titles": [
        {
          "name": "Buffalo Sabres",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/buffalo-sabres.jpg",
          "summary": ""
        },
        {
          "name": "Colorado Avalanches",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/colorado-avalanches.jpg",
          "summary": ""
        },
        {
          "name": "Dallas Stars",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/dallas-stars.jpg",
          "summary": ""
        },
        {
          "name": "Pittsburgh Penguins",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/pittsburgh-penguins.jpg",
          "summary": ""
        },
        {
          "name": "Seattle Kraken",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/seattle-kraken.jpg",
          "summary": ""
        },
        {
          "name": "Toronto Maple Leafs",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/toronto-maple-leafs.jpg",
          "summary": ""
        },
        {
          "name": "Vegas Knights",
          "image": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Interest/vegas-knights.jpg",
          "summary": ""
        }
      ]
    }
  ]
}

###

GET http://localhost:8080/employment

###

GET http://localhost:8080/employment/1232421312312323

###

POST http://localhost:8080/employment HTTP/1.1
Content-Type: application/json

{
    "_id": 1232421312312323,
    "first_name": "Stewart",
    "middle_intial": "M",
    "last_name": "Rowley",
    "phone_number": "509-301-0726",
    "email": "row16006@byui.edu",
    "linkedin_url": "www.linkedin.com/in/stewartmrowley",
    "resume": "https://drive.google.com/file/d/1xdnKUj9ZjUIMlBUI3C_fp7QAl1EJPLKY/view?usp=sharing",
    "education": [{
        "college": "Brigham Young University - Idaho",
        "degree_type": "Bachelor's Degree",
        "degree": "Software Engineering",
        "emphasis": "Web Development",
        "start_date": "September 2018",
        "end_date": "December 2022",
        "location": "Rexburg, Idaho",
        "tools": ["HTML", "CSS", "Javascript", "React Js", "Vue Js", "Php"]
    }],
    "professional_experience": [{
        "company": "Nelson Irrigation Corporation",
        "job_title": "Software Engineering and Web Development Intern",
        "tasks": [
            {
                "task_name": "Web Development",
                "task_description": ["created custom website utilizing React Js and Node Js for customers to track past, current, and future data for over 1000 custom systems"]
            },
            {
                "task_name":"Web Design",
                "task_description": ["Created custom website that auto-populated charts and graphs to demonstrate customers water usage and output"]
            },
            {
                "task_name":"Software Engineer",
                "task_description": ["Analyzed python scripts that capture over 10,000 data points", "Utilized custom applications using complex algorithms to calculate water distribution", "Ran Python Scripts that applied information into Excel and XML files Maintained functionality"]
            }
        ],
        "start_date": "June 2021",
        "end_date": "August 2022",
        "location": "Walla Walla, WA"
    }],
    "work_experience": [{
        "company": "Rowley's Wholesale Plant, Nursery and Produce",
        "job_title": "Manager/Farm Hand",
        "tasks": [
            {
                "task_name": " ",
                "task_description": ["Independently managed and operated heavy farm equipment including forklifts, tractors and cherry shakers","Managed 15+ workers and co-managed operations for over 1,000,000 pounds of produce annually", "Maintained functionality and sustainability of irrigation systems for over 80 acres of orchards"]
            }
        ],
        "start_date": "January 2011",
        "end_date": "August 2021",
        "location": "Walla Walla, WA"
    }],
    "personal_experience": [{
        "name": "Volunteer for The Church of Jesus Christ of Latter-day",
        "title": "Full-Time Missionary",
        "tasks": ["Logged over 4,000 hours of voluntarily helping strangers with an enthusiastic and compassionate attitude as I interacted with, served, and taught customized lessons", "Managed lesson planning, daily schedules, communication and travel for an area with over 10,000 people"],
        "start_date": "August 2016",
        "end_date": "August 2018",
        "location": "Fort Worth Texas"    
    }],
    "skills": [
        {
            "skill_category": "Coding, Systems and Platforms",
            "skill_description": ["Python – Object Orientated Programming, MySQL, HTML, CSS, JavaScript, Php, Java"]
        },
        {
            "skill_category": "Coding Skills",
            "skill_description": ["Language - Python, Java, C, Kotlin", "Web Development – HTML, CSS, Javascript, React Js, Node Js"]
        },
        {
            "skill_category": "Systems and Platform Skills",
            "skill_description": ["App Development – exploring Android Studio", "Operating Systems – Windows, Linux, Unix", "Cloud Platform – MongoDB", "Database – Access, Excel, Xml, SQL", "Version Controls -Git Github, Git Lab, Sourcetree"]
        }
    ]
}

###

PUT http://localhost:8080/employment/1232421312312323 HTTP/1.1
Content-Type: application/json

{
    "_id": 1232421312312323,
    "first_name": "Stewart",
    "middle_intial": "M",
    "last_name": "Rowley",
    "phone_number": "509-301-0726",
    "email": "row16006@byui.edu",
    "linkedin_url": "www.linkedin.com/in/stewartmrowley",
    "education": [{
        "college": "Brigham Young University - Idaho",
        "degree_type": "Bachelor's Degree",
        "degree": "Software Engineering",
        "emphasis": "Web Development",
        "start_date": "September 2018",
        "end_date": "December 2022",
        "location": "Rexburg, Idaho",
        "tools": ["HTML", "CSS", "Javascript", "React Js", "Vue Js", "Php"]
    }],
    "professional_experience": [{
        "company": "Nelson Irrigation Corporation",
        "job_title": "Software Engineering and Web Development Intern",
        "tasks": [
            {
                "task_name": "Web Development",
                "task_description": ["created custom website utilizing React Js and Node Js for customers to track past, current, and future data for over 1000 custom systems"]
            },
            {
                "task_name":"Web Design",
                "task_description": ["Created custom website that auto-populated charts and graphs to demonstrate customers water usage and output"]
            },
            {
                "task_name":"Software Engineer",
                "task_description": ["Analyzed python scripts that capture over 10,000 data points", "Utilized custom applications using complex algorithms to calculate water distribution", "Ran Python Scripts that applied information into Excel and XML files Maintained functionality"]
            }
        ],
        "start_date": "June 2021",
        "end_date": "August 2022",
        "location": "Walla Walla, WA"
    }],
    "work_experience": [{
        "company": "Rowley's Wholesale Plant, Nursery and Produce",
        "job_title": "Manager/Farm Hand",
        "tasks": [
            {
                "task_name": null,
                "task_description": ["Independently managed and operated heavy farm equipment including forklifts, tractors and cherry shakers","Managed 15+ workers and co-managed operations for over 1,000,000 pounds of produce annually", "Maintained functionality and sustainability of irrigation systems for over 80 acres of orchards"]
            }
        ],
        "start_date": "January 2011",
        "end_date": "August 2021",
        "location": "Walla Walla, WA"
    }],
    "personal_experience": [{
        "name": "Volunteer for The Church of Jesus Christ of Latter-day",
        "title": "Full-Time Missionary",
        "tasks": ["Logged over 4,000 hours of voluntarily helping strangers with an enthusiastic and compassionate attitude as I interacted with, served, and taught customized lessons", "Managed lesson planning, daily schedules, communication and travel for an area with over 10,000 people"],
        "start_date": "August 2016",
        "end_date": "August 2018",
        "location": "Fort Worth Texas"    
    }],
    "skills": [
        {
            "skill_category": "Coding, Systems and Platforms",
            "skill_description": ["Python – Object Orientated Programming, MySQL, HTML, CSS, JavaScript, Php, Java"]
        },
        {
            "skill_category": "Coding Skills",
            "skill_description": ["Language - Python, Java, C, Kotlin", "Web Development – HTML, CSS, Javascript, React Js, Node Js"]
        },
        {
            "skill_category": "Systems and Platform Skills",
            "skill_description": ["App Development – exploring Android Studio", "Operating Systems – Windows, Linux, Unix", "Cloud Platform – MongoDB", "Database – Access, Excel, Xml, SQL", "Version Controls -Git Github, Git Lab, Sourcetree"]
        }
    ]
}

###

GET http://localhost:8080/gallery

###

GET http://localhost:8080/gallery/1232421312312323

###

POST http://localhost:8080/gallery HTTP/1.1
Content-Type: application/json

{
  "_id": 1232421312312323,
  "images_url": [
    {
      "vertical_images": [
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_1896.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_1896b.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_1914.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_1914b.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_1921.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_1933-2.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2032.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2095.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2095b.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2103.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2105.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2114.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Emily",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2148.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Emily",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2148b.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2172.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2206.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2206b.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2231.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2317.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_6199.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_6199b.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_6216.jpg"
        },
        {
          "title": "Family",
          "sub_title": "Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_6216b.jpg"
        }
      ],
      "horizontal_images": [
        {
          "title": "Family",
          "sub_title": "Stewart, Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2010.png"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2285.png"
        },
        {
          "title": "Family",
          "sub_title": "Stewart & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2285b.png"
        },
        {
          "title": "Family",
          "sub_title": "Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2335.png"
        },
        {
          "title": "Family",
          "sub_title": "Emily & Abigail",
          "image_url": "https://raw.githubusercontent.com/stewartrowley/portfolio-project/main/frontend/src/images/Gallery/IMG_2335b.png"
        }
      ]
    }
  ]
}

###

GET http://localhost:8080/message

###

POST http://localhost:8080/message HTTP/1.1
Content-Type: application/json

{
    "firstName": "Stewart",
    "lastName": "Rowley",
    "email": "row16006@byui.edu",
    "phoneNumber": "509-301-0726",
    "message": "Hello there"
}

###