GET http://localhost:8080/person

###

GET http://localhost:8080/person/1232421312312323

###

POST http://localhost:8080/person HTTP/1.1
Content-Type: application/json

{
    "_id": 1232421312312323,
    "firstName": "Stewart",
    "lastName": "Rowley",
    "career": "Web Development",
    "degree": "Software Engineering",
    "location": "Walla Walla, Washington"
}

###

GET http://localhost:8080/about

###

GET http://localhost:8080/about/1232421312312323

###

POST http://localhost:8080/about HTTP/1.1
Content-Type: application/json

{
  "_id": 1232421312312323,
  "firstName": "Stewart",
  "lastName": "Rowley",
  "career": "Web Development",
  "degree": "Software Engineering",
  "location": "Walla Walla, Washington",
  "introduction": "I was born in Walla Walla, Washington in 1998. The family I grew up in was 9 siblings including me. I had 4 brothers and 4 sisters. I am the third youngest in my famliy. I met my wife in Walla Walla Washington before I left for a 2 year mission for the church of Jesus Christ. I went on a mission for the church of Jesus Christ in Fort Woth, Texas. After my mission I got married to Emily Hepworth. I went to college at BYU-Idaho to get my Bachelors degree in Software Engineering. With an emphasis in the Web development. I have a passion for Web Development and love doing it. ",
  "interest": [
    {
      "name": "Movies",
      "description": "These are some of the following favorite movies I like, as follows:",
      "titles": ["How to Train Your Dragon", "Star Wars: Return of the Jedi", "Shang Chi"]
    },
    {
      "name": "Board Games",
      "description": "I have found board games to be one of my favorite things to do with others. Here are some of my favorite Board games, as follows: ",
      "titles": ["Scythe", "Pandemic", "Wingspan"]
    },
    {
      "name": "NHL Hockey",
      "description": "I love watching NHL hockey and I also love doing fantasy hockey. My most favorite team is the Seattle Kraken but I do love some other teams to. These are the teams as follows:",
      "titles": [
        "Buffalo Sabres",
        "Colorado Avalanches",
        "Dallas Stars",
        "Pittsburgh Penguins",
        "Seattle Kraken",
        "Toronto Maple Leafs",
        "Vegas Knights"
      ]
    }
  ]
}

###

PUT http://localhost:8080/about/1232421312312323 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Stewart",
    "lastName": "Rowley",
    "career": "Web Development",
    "degree": "Software Engineering",
    "location": "Walla Walla, Washington",
}

###

GET http://localhost:8080/employment

###

GET http://localhost:8080/employment/1232421312312323

###

POST http://localhost:8080/employment HTTP/1.1
Content-Type: application/json

{
    "_id": 1232421312312323,
    "first_name": "Stewart",
    "middle_intial": "M",
    "last_name": "Rowley",
    "phone_number": "509-301-0726",
    "email": "row16006@byui.edu",
    "linkedin_url": "www.linkedin.com/in/stewartmrowley",
    "education": [{
        "college": "Brigham Young University - Idaho",
        "degree_type": "Bachelor's Degree",
        "degree": "Software Engineering",
        "emphasis": "Web Development",
        "start_date": "September 2018",
        "end_date": "December 2022",
        "location": "Rexburg, Idaho",
        "tools": ["HTML", "CSS", "Javascript", "React Js", "Vue Js", "Php"]
    }],
    "professional_experience": [{
        "company": "Nelson Irrigation Corporation",
        "job_title": "Software Engineering and Web Development Intern",
        "tasks": [
            {
                "task_name": "Web Development",
                "task_description": ["created custom website utilizing React Js and Node Js for customers to track past, current, and future data for over 1000 custom systems"]
            },
            {
                "task_name":"Web Design",
                "task_description": ["Created custom website that auto-populated charts and graphs to demonstrate customers water usage and output"]
            },
            {
                "task_name":"Software Engineer",
                "task_description": ["Analyzed python scripts that capture over 10,000 data points", "Utilized custom applications using complex algorithms to calculate water distribution", "Ran Python Scripts that applied information into Excel and XML files Maintained functionality"]
            }
        ],
        "start_date": "June 2021",
        "end_date": "August 2022",
        "location": "Walla Walla, WA"
    }],
    "work_experience": [{
        "company": "Rowley's Wholesale Plant, Nursery and Produce",
        "job_title": "Manager/Farm Hand",
        "tasks": [
            {
                "task_name": " ",
                "task_description": ["Independently managed and operated heavy farm equipment including forklifts, tractors and cherry shakers","Managed 15+ workers and co-managed operations for over 1,000,000 pounds of produce annually", "Maintained functionality and sustainability of irrigation systems for over 80 acres of orchards"]
            }
        ],
        "start_date": "January 2011",
        "end_date": "August 2021",
        "location": "Walla Walla, WA"
    }],
    "personal_experience": [{
        "name": "Volunteer for The Church of Jesus Christ of Latter-day",
        "title": "Full-Time Missionary",
        "tasks": ["Logged over 4,000 hours of voluntarily helping strangers with an enthusiastic and compassionate attitude as I interacted with, served, and taught customized lessons", "Managed lesson planning, daily schedules, communication and travel for an area with over 10,000 people"],
        "start_date": "August 2016",
        "end_date": "August 2018",
        "location": "Fort Worth Texas"    
    }],
    "skills": [
        {
            "skill_category": "Coding, Systems and Platforms",
            "skill_description": ["Python – Object Orientated Programming, MySQL, HTML, CSS, JavaScript, Php, Java"]
        },
        {
            "skill_category": "Coding Skills",
            "skill_description": ["Language - Python, Java, C, Kotlin", "Web Development – HTML, CSS, Javascript, React Js, Node Js"]
        },
        {
            "skill_category": "Systems and Platform Skills",
            "skill_description": ["App Development – exploring Android Studio", "Operating Systems – Windows, Linux, Unix", "Cloud Platform – MongoDB", "Database – Access, Excel, Xml, SQL", "Version Controls -Git Github, Git Lab, Sourcetree"]
        }
    ]
}

###

PUT http://localhost:8080/employment/1232421312312323 HTTP/1.1
Content-Type: application/json

{
    "_id": 1232421312312323,
    "first_name": "Stewart",
    "middle_intial": "M",
    "last_name": "Rowley",
    "phone_number": "509-301-0726",
    "email": "row16006@byui.edu",
    "linkedin_url": "www.linkedin.com/in/stewartmrowley",
    "education": [{
        "college": "Brigham Young University - Idaho",
        "degree_type": "Bachelor's Degree",
        "degree": "Software Engineering",
        "emphasis": "Web Development",
        "start_date": "September 2018",
        "end_date": "December 2022",
        "location": "Rexburg, Idaho",
        "tools": ["HTML", "CSS", "Javascript", "React Js", "Vue Js", "Php"]
    }],
    "professional_experience": [{
        "company": "Nelson Irrigation Corporation",
        "job_title": "Software Engineering and Web Development Intern",
        "tasks": [
            {
                "task_name": "Web Development",
                "task_description": ["created custom website utilizing React Js and Node Js for customers to track past, current, and future data for over 1000 custom systems"]
            },
            {
                "task_name":"Web Design",
                "task_description": ["Created custom website that auto-populated charts and graphs to demonstrate customers water usage and output"]
            },
            {
                "task_name":"Software Engineer",
                "task_description": ["Analyzed python scripts that capture over 10,000 data points", "Utilized custom applications using complex algorithms to calculate water distribution", "Ran Python Scripts that applied information into Excel and XML files Maintained functionality"]
            }
        ],
        "start_date": "June 2021",
        "end_date": "August 2022",
        "location": "Walla Walla, WA"
    }],
    "work_experience": [{
        "company": "Rowley's Wholesale Plant, Nursery and Produce",
        "job_title": "Manager/Farm Hand",
        "tasks": [
            {
                "task_name": null,
                "task_description": ["Independently managed and operated heavy farm equipment including forklifts, tractors and cherry shakers","Managed 15+ workers and co-managed operations for over 1,000,000 pounds of produce annually", "Maintained functionality and sustainability of irrigation systems for over 80 acres of orchards"]
            }
        ],
        "start_date": "January 2011",
        "end_date": "August 2021",
        "location": "Walla Walla, WA"
    }],
    "personal_experience": [{
        "name": "Volunteer for The Church of Jesus Christ of Latter-day",
        "title": "Full-Time Missionary",
        "tasks": ["Logged over 4,000 hours of voluntarily helping strangers with an enthusiastic and compassionate attitude as I interacted with, served, and taught customized lessons", "Managed lesson planning, daily schedules, communication and travel for an area with over 10,000 people"],
        "start_date": "August 2016",
        "end_date": "August 2018",
        "location": "Fort Worth Texas"    
    }],
    "skills": [
        {
            "skill_category": "Coding, Systems and Platforms",
            "skill_description": ["Python – Object Orientated Programming, MySQL, HTML, CSS, JavaScript, Php, Java"]
        },
        {
            "skill_category": "Coding Skills",
            "skill_description": ["Language - Python, Java, C, Kotlin", "Web Development – HTML, CSS, Javascript, React Js, Node Js"]
        },
        {
            "skill_category": "Systems and Platform Skills",
            "skill_description": ["App Development – exploring Android Studio", "Operating Systems – Windows, Linux, Unix", "Cloud Platform – MongoDB", "Database – Access, Excel, Xml, SQL", "Version Controls -Git Github, Git Lab, Sourcetree"]
        }
    ]
}

###